apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "research-pool"
spec:
  blocks:
    - start: "10.89.0.230"
      stop: "10.89.0.254"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
spec:
  externalIPs: true
  loadBalancerIPs: true
  interfaces:
    - eth0
